all_branches: true

language:
  sh
  python

python:
  - "2.7"

sudo: required

cache: apt

services:
  - docker

notifications:
  slack: eftcamb:c0M48rajcf8rkANZsQCAHoaF

before_install:
  - docker pull eftcamb/eftbox

env:
  global:
  - ENCRYPTION_LABEL: "978549549c67"
  - COMMIT_AUTHOR_EMAIL: "mraveri@sissa.it"

script:
  - while true; do echo 'Travis do not sleep!'; sleep 300s; done &
  - TIME_PID=$!
  #- docker run -v $(pwd):$(pwd) -t eftcamb/eftbox /bin/sh -c "cd $(pwd) ; make all"
  - docker run -v $(pwd):$(pwd) -t eftcamb/eftbox /bin/sh -c "cd $(pwd) ; make eftcamb_doc"
  - kill $TIME_PID

after_success:
  - docker run -v $(pwd):$(pwd) -e ENCRYPTION_LABEL -e encrypted_$ENCRYPTION_LABEL_key -e encrypted_$ENCRYPTION_LABEL_iv -e COMMIT_AUTHOR_EMAIL -e TRAVIS_PULL_REQUEST -e TRAVIS_BRANCH -t eftcamb/eftbox /bin/sh -c "cd $(pwd) ; bash $(pwd)/eftcamb_doc/deploy_doc.sh "
